name: "IL-IA"
description: "Service d'IA prédictive pour optimiser le chauffage"
version: "0.0.1"
slug: "predictive_heating"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  7777/tcp: 7777
