name: "IL-IA"
description: "Service d'IA prédictive pour optimiser le chauffage"
version: "0.0.2"
slug: "IL_IA"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  7777/tcp: 7777
